language: r
sudo: false
os:
  - linux
cache:
  packages: true
r:
  - bioc-devel
before_install:
  - tlmgr install index

  # install:
#   R -e 'install.packages("BiocManager"); BiocManager::install(version = "3.10", ask=FALSE); BiocManager::install(c("TENxPBMCData", "DropletUtils", "scater", "scran", "igraph", "devtools", "tidyr", "tensorflow"), version = "devel", ask = FALSE); devtools::install_github("irrationone/cellassign")'

# language: r
# sudo: false
# os:
#   - linux
# cache:
#   packages: true
# r:
#   - bioc-devel
# before_install:
#   - tlmgr install index

