language: r
sudo: false
os:
  - linux
cache:
  packages: true
r:
  - bioc-devel
before_install:
  - tlmgr install index
script:
  echo "This will take too long to compile."
# script:
# - travis_wait 45 R -e 'devtools::check()'
