language: r
sudo: false
os:
  - linux
cache:
  packages: true
r:
  - bioc-devel
before_install:
  - tlmgr install index

  
# script:
#   echo "hello world, I'mma install all the pkgs"

  
# install:
#   R -e 'install.packages(c("devtools", "KernSmooth", "qpdf", "uwot", "pheatmap")); devtools::install_github("irrationone/cellassign"); BiocManager::install(c("SingleCellExperiment", "TENxPBMCData", "DropletUtils", "scater", "scran", "tidyr", "iSEE", "tensorflow", "BiocParallel"), version = "devel", ask = FALSE)'

# BiocManager::install(version = "3.10", ask=FALSE); 

# language: r
# sudo: false
# os:
#   - linux
# cache:
#   packages: true
# r:
#   - bioc-devel
# before_install:
#   - tlmgr install index

