language: r
sudo: false
os:
  - linux
cache:
  packages: true
install:
  R -e 'install.packages("BiocManager"); BiocManager::install(version = "3.10", ask=FALSE); BiocManager::install(c("SingleCellExperiment", "scater", "scran", "batchelor"), version = "devel", ask = FALSE)'
before_install:
  - tlmgr install index
